# Generated by Django 5.2.3 on 2025-11-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobalt_strike_monitor', '0030_auto_20250317_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='beaconlog',
            name='task_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]

