# Generated by Django 5.1.7 on 2025-05-15 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_tracker', '0084_operation_alter_userpreferences_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event_tracker.operation')),
            ],
        ),
    ]
