# Generated by Django 5.1.7 on 2025-05-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_tracker', '0086_ldapsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='ldapsettings',
            name='tls_cacertfile',
            field=models.CharField(blank=True, help_text='Path to CA certificate file for LDAPS', max_length=255),
        ),
        migrations.AddField(
            model_name='ldapsettings',
            name='tls_demand',
            field=models.IntegerField(default=0, help_text='Value for ldap.OPT_X_TLS_DEMAND (usually 0 or 1)'),
        ),
        migrations.AddField(
            model_name='ldapsettings',
            name='tls_require_cert',
            field=models.IntegerField(default=0, help_text='Value for ldap.OPT_X_TLS_REQUIRE_CERT (e.g., 0 for never, 1 for allow, 2 for demand, 3 for hard, 4 for try)'),
        ),
    ]
