# Generated by Django 5.1.7 on 2025-11-07 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_tracker', '0087_ldapsettings_tls_cacertfile_ldapsettings_tls_demand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='operation',
            field=models.ForeignKey(blank=True, help_text='The operation this credential belongs to. If null, credential is shared across all operations.', null=True, on_delete=django.db.models.deletion.CASCADE, to='event_tracker.operation'),
        ),
        migrations.AlterUniqueTogether(
            name='credential',
            unique_together={('operation', 'system', 'account', 'hash', 'hash_type')},
        ),
    ]


