# Generated by Django 5.2.3 on 2025-07-09 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_tracker', '0084_alter_credential_hash'),
        ('event_tracker', '0087_ldapsettings_tls_cacertfile_ldapsettings_tls_demand_and_more'),
    ]

    operations = [
    ]
