# Generated by Django 6.1.7 on 2025-11-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_tracker', '0088_credential_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='hash',
            field=models.CharField(blank=True, db_collation='nocase', help_text='A hashed version of the secret, in a form usable by hashcat', max_length=10000, null=True),
        ),
    ]
